importScripts(
  "vendor/webextension-polyfill/browser-polyfill.min.js",
  "js/engine/version.js",
  "js/engine/rules/generic.js",
  "js/engine/rules/sites.js",
  "js/engine/rules/dom.js",
  "js/engine/verify.js",
  "js/engine/core.js",
  "js/lib/discord.js",
  "js/lib/storage.js",
  "js/background.js"
);
