importScripts(
  "vendor/webextension-polyfill/browser-polyfill.min.js",
  "vendor/maxurl/userscript_smaller.user.js",
  "js/lib/url-rules.js",
  "js/lib/srcset.js",
  "js/lib/discord.js",
  "js/lib/storage.js",
  "js/lib/imu.js",
  "js/background.js"
);
